### ISSUE TITLE
Add the feature to convert txt files

### ISSUE THREAD

**Issue by ddotta** [ddotta/parquetize#11]

**Comment by etiennebacher** [comment]
Hi @ddotta this feature would be useful, was it implemented? I can't find a function `txt_to_parquet()` or similar

**Comment by ddotta** [comment]
Hi @etiennebacher  
At the moment there is only the `csv_to_parquet()` function.
Could you provide an example of a reproducible text file that would be interesting for parquetize to support for conversion?

**Comment by etiennebacher** [comment]
Any data in a `.txt` format?
```r
write.table(iris, "test.txt")
```
To give more context I just obtained some large census data that is stored as .txt so having something that automatically converts these text files to parquet (if possible by batches) would be useful

**Comment by ddotta** [comment]
@etiennebacher

**Comment by etiennebacher** [comment]
Thanks, I was deceived by the function name 😄
