### ISSUE TITLE
rds gzfile cannot open connection

### ISSUE THREAD

**Issue by ChristosMichaliaslis** [ddotta/parquetize#51]
Hello, I had some problems converting rds files to parquet with the rds_to_parquet function. My working directory is the same with the directory of the rds file and the directory to save the parquet file.
I am having the following code:

rds_to_parquet(
   path_to_file = system.file('file path on the computer', 'file name',
                                             package = 'parquetize'),
   path_to_parquet = tempfile(name for the parquet file',
                                                tmpdir = 'directory to save the parquet file',
                                                fileext = '.parquet'))

And I get the following error

Error in gzfile(file, "rb") : cannot open the connection
In addition: warning message:
In gzfile(file, "rb") : 
cannot open the compressed file ' ', probably reason 'Invalid argument'

I really would appreciate some help here because I don't know what to do.
Thanks in advanced.

**Comment by nbc** [comment]
Hi,

I'm try to look a this tomorrow.

**Comment by nbc** [comment]
I can't reproduce your error.

Can you post a real piece of code that produce it ?

**Comment by ChristosMichaliaslis** [comment]
Hi , this is the code with all the feature being the same as I wrote in the post!
Unfortunately, I cannot share the file.

![rds_to_parq](https://github.com/ddotta/parquetize/assets/151936766/d3c17567-2d23-4359-920c-bf949698d905)

**Comment by nbc** [comment]
The problem seems to be in the first blurred part that seems to return a empty file name.

Are you sure you need to use  `system.file(<blurred>, package = "parquetize")` ?  `system.file` is used to find files relating to package : https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/system.file

**Comment by ChristosMichaliaslis** [comment]
That was the problem indeed. Thank you very much for helping me, now it worked correctly.
