### ISSUE TITLE
Replace read_delim by read_delim_arrow

### ISSUE THREAD

**Issue by ddotta** [ddotta/parquetize#56]
In `csv_to_parquet()` function, it would be graet to replace [read_delim()](https://readr.tidyverse.org/reference/read_delim.html) from {readr} with [read_delim_arrow()](https://arrow.apache.org/docs/r/reference/read_delim_arrow.html) from arrow, which would improve performance.

**Comment by ddotta** [comment]
Discarded for now, I can't figure out how to do the equivalent with `read_delim_arrow()` of [this feature](https://github.com/ddotta/parquetize/blob/main/R/csv_to_parquet.R#L19) 

To be explored

**Comment by ds-turner** [comment]
Either of the following should pass the list on I think.

```
fun <- function(file, other_args = list()) {
  do.call(arrow::read_delim_arrow, c(file, other_args))
}

fun2 <- function(file, other_args = list()) {
  rlang::inject(arrow::read_delim_arrow(file, !!!other_args))
}

# testing
url <- "https://github.com/tidyverse/readr/raw/main/inst/extdata/mtcars.csv"

bench::mark(
  fun(url),
  fun2(url),
  arrow::read_delim_arrow(url)
)

bench::mark(
  fun(url, list(col_names = F, skip = 10)),
  fun2(url, list(col_names = F, skip = 10)),
  arrow::read_delim_arrow(url, col_names = F, skip = 10)
)
```
